<!-- js -->
		<!-- Page info -->
		<header class="site-title color">
			<div class="wrap">
				<div class="container">
					<h1 style="color:white">Terms Of Services</h1>
					
				</div>
			</div>
		</header>
	<!-- //Preloader -->
	
    <!-- Header -->
	<!-- //Header -->
	
	<!-- Main -->
	<main class="main" role="main">
		<!-- //Page info -->
		
		
		<div class="wrap">
			<div class="row">				
				<!--- Content -->
				<div class="three-fourth content">
					<!-- Post -->
	
                        <article class="single hentry">
						<div class="entry-content">
							<p style="text-align:justify;"><b>This document is an electronic record in terms of Information Technology Act, 2000 and
rules there under as applicable and the amended provisions pertaining to electronic
records in various statutes as amended by the Information Technology Act, 2000. This
electronic record is generated by a computer system and does not require any physical or
digital signatures.</b></p> 
					<p style="text-align:justify;" >Welcome to our website/application. The brand "Xpress Move", domain www.xpressmove.in, mobile
application "Xpress Move" are owned by Socios, a partnership firm, registered in Pune. If you
continue to browse and use Xpress Move's website/application you agree to comply with and
generally by the following terms and conditions which govern together with our privacy policy
from Xpress Move relationship with you in connection with the site/application and the services.
"We", "us", "our", "Carrier", “Xpress Move” shall refer to Socios (a partnership firm), its
employees, authorized agents and its independent contractors and the entities that carry or
undertake to carry the consignment hereunder or perform any other services incidental thereto on
its behalf.</p> 
					<p style="text-align:justify;">These terms and conditions ( <b>ServiceUser terms</b>) apply on the usage of our website www.xpressmove.in (the <b>"Website"</b> ), smart phone Xpress Move Application
(the <b>Application</b>) as well as to all information, recommendations and/or services provided to you
on or through the <b>Website, the Application</b> or through the <b>Customer Care (The CC)</b> through a
phone number +918698123444.
The term <b>'YOU'</b> refers to the user of our services through
Website, the Application and the <b>CC</b>. The terms and conditions mentioned in this contract along
with the Privacy Policy constitute the entire contract between the User(s) and Xpress Move with
respect to access to and use of the website / application and the Services offered by Xpress Move,
superseding any prior written or oral contracts in relation to the same subject matter herein.</p>  
                            <h2>The Service</h2>
                            <p style="text-align:justify;">Xpress Move offers a technology platform on www.xpressmove.in and Mobile Application Xpress Move available on Google Play store. Xpress Move’s Technology platform is an enabling
platform for a consumer to connect with a third party, independent valid permit holder drivers or
vehicle operators known as T he Transport Service Provider hereinafter referred as TSP. Once
TSP accepts a request, customer is notified with the details of TSP through sms, call or mobile
application.</p> 
                                                 <p style="text-align:justify;">Although Xpress Move shall do all the reasonable efforts to connect you with a TSP & the services
are subject to the availability of TSPs in or around your location at the moment of your request
for transportation services but Xpress Move does not guarantee the availability of the Services, the availability of vehicles through the use of the Services, the accuracy of the data or information
provided as part of the Services or the quality of the services of the Participating vehicles</p> 
                                  <p style="text-align:justify;"><b>By using this website and/or Mobile Application or user of the service through The CC you
hereby acknowledges that Xpress Move</b> is not a transport services provider.
It is up to the <b>TSP</b> to offer transportation services, which may be requested through the use of
the Website, Application or CC. Xpress Move only acts an intermediary between you and the TSP .
The user has to note that <b>TSP</b> is your service provider and therefore it is subjected to the contract
between <b>YOU</b> and the <b>TSP</b> . Xpress Move shall never be a party to such contract.</p>
                            <h2>User(s) Eligibility</h2>
                             <p style="text-align:justify;">User(s) means any individual or business entity/organization that legally operates in India or in
other countries, uses and has the right to use the services provided by Xpress Move. Our Services
are available only to those individuals or companies who can form legally binding contracts
under the applicable law. Therefore, user(s) must not be a minor as per Indian Law; i.e. user(s)
must be at least 18 years of age to be eligible to use our Services.</p>
                                                         <p style="text-align:justify;">Xpress Move advises its users that while accessing the web site/ the application, they must
follow/abide by the related laws. Xpress Move is not responsible for the possible consequences
caused by your behavior during use of web site/application. Xpress Move at all the times reserves
the right to deny service.</p>
                            <h2>User Accounts, Offers And Promotions</h2>
                                                                            <p style="text-align:justify;">Xpress Move collects general user data including name, email ID, contact details etc. to facilitate
services. It is assumed that all information collected from the user is Correct & Accurate. Misuse
and misrepresentation of identity or contact details will lead to automated termination of services
or the use of the platform without prior notice to such users.</p>
                                                                          <p style="text-align:justify;">User accounts bearing contact number and email IDs are created and owned by Xpress Move. The
company has right to use the customer contact information for marketing purposes. The
Company may send regular SMS updates to the phone numbers registered with it. Any
promotional discounts, offers and reward points in the form of cash back or Xpress Move Money
accumulated can be revoked without prior notice in the event of suspicious account activity or
malafide intent of the user. In the case where the system is unable to establish unique identity of
the user against a valid mobile number or email
ID, the account shall be indefinitely suspended.
Xpress Move reserves the full discretion to suspend a user's account n the above event and does not
have the liability to share any account information whatsoever.</p>
                            <h2>Software</h2>
                             <p style="text-align:justify;">Any software made a vailable to work on this website or on a mobile device and / or to download
information and resources from it ( the " Software " ) is owned and copyrighted work of the Company and / or its affiliates . You are entitled to use the Software solely for the purpose of
visiting the site , and / or downloading of information and resources , from him or make
necessary service bookings . You can use this software only for the purpose mentioned above.
Under no circumstances , you shall distribute to restructure , sell , decompile , reverse engineer ,
disassemble or otherwise deal with the Software .</p>
                                           <p style="text-align:justify;">The site / application is supplied on "as is " and indeed Xpress Move is its best
endeavors to ensure that the application to work correctly on your mobile device , though Xpress
Move does not guarantee the performance of the application , nor the compatibility of the
application with your mobile device . Xpress Move shall not be liable for any damages, claims or
costs of any kind, including consequential, indirect, incidental damages or lost profits or damage
to your mobile device as a result of your use of the Services or the installation and / or execution
of software, even if Xpress Move or his representative was informed of the possibility of such loss,
damage or claims.</p>
                            <h2>Website/Application As An Intermediary Platform</h2>
                                                          <p style="text-align:justify;">Xpress Move’s Website, Application, Customer Care are just intermediary platforms that users utilize to
meet and interact with one another and Vendors for required transportation service.</p>
                            <ul style="list-style-type:circle;margin-left:20px;" >
                     <li>All communication which inter alia include booking, its terms, your obligations, the
vendor’s obligations, etc are outcomes of the communication between the vendor and
You (through us). This includes, without any limitation, the details, date, and warranties
related to services after booking/reservation. We do not have any control over such
information and play no determinative role in the finalization of the same and hence do
not stand liable for the outcomes of such communication.</li>
                                <li>Subject to the above subclauses,
a contract exists between the Vendor and the User and
as such any breach of contract and thus, any claim arising from such breach is the subject
matter of the Vendor and the User alone and we are in no way a party to such breach or
involved in any suit arising from the same breach. The contact/communication arising
from such breach may entail between the Vendor and the User directly without us being
involved.</li>
                                <li>We act as mere facilitators who make available labour as per your requirements. As set
forth above, such contract between the User and the labour does not include us, and we
are in no way liable for any deficiency of service that may arise which includes and is not
limited to cancellation of the reservation due to nonavailability,
services not meeting
expectations of the User, and poor quality.</li>
                                <li>Due to some technical issue, or typographical error, pricing on any product(s) or services
as is reflected on the website by vendor may be incorrect and in such an event the vendor
may cancel such reservations made by you.</li>
                                <li>You release and indemnify us and/or any of our officers and representatives from any
cost, damage, liability or other consequence of any of your actions on the Website and
specifically waive any claims that you may have in this behalf under any applicable law.</li>
                     </ul>
                            <h2>Usage Conditions</h2>
                            <p style="text-align:justify;">You are advised to provide accurate information to Xpress Move. Xpress Move can verify the
information that you have provided and choose to refuse the service or use of the Application /
the Website without providing reasons.</p>
                                            <p><b>By using the Application or Website you agree to:</b></p>
                                    <ul style="list-style-type:circle;margin-left:20px;" >
                     <li>You have understood your contract with Xpress Move for Website / Application usage and you
have clearly understood the SERVICE with our CLARIFICATIONS.</li>
                                <li>Use the Application for personal purpose only.</li>
                                <li>You will not assign or otherwise transfer your account to any other person or legal entity.</li>
                                <li>You will not use the Service or Application for unlawful purposes, including but not limited
to sending or storing any unlawful material or for fraudulent purposes.</li>
                                <li>You will not use the Service or Application to cause nuisance, annoyance or inconvenience.</li>
                                         <li>You will not impair the proper operation of the network.</li>
                                         <li>You will not try to harm the Service or Application in any way whatsoever.</li>
                                         <li>You will not copy, or distribute the Application or other content of Xpress Move without
written permission from Xpress Move.</li>
                                         <li>You will keep your account password information confidential or Any other identification we
provide you which allows access to the Service and the Application.</li>
                                         <li>You will provide us with whatever proof of identity we may reasonably request.</li>
                                                                         <li>You will comply with all applicable law from your city, State and the country while using the
Application or the Service.</li>
                                          </ul>
                                           <p style="text-align:justify;">In addition to other reasons mentioned under the Termination clause below, Xpress Move reserves
the right to immediately terminate the Service and the use of the Application should you not
comply with any of the above rules.</p>
                            
                            <h2>General Customer Behaviour While Using Transport Service
Through Transport Service Provider</h2>
                            <p style="text-align:justify;">It is expressly made clear to the customers that the Xpress Move does not own any vehicle
registered with it for logistics purpose, nor does it directly or indirectly employ any drivers for the vehicle. Vehicle and drivers are all supplied by third parties and the Company disclaims any
and all liability in respect of the drivers and the Vehicle alike.</p>
                             <ul style="list-style-type:circle;margin-left:20px;" >
                     <li>You have understood your contract with Xpress Move for Website / Application usage and you
have clearly understood the SERVICE with our CLARIFICATIONS.</li>
                                <li>It is expected that a reasonable behavior shall be followed by the customers / passengers
while utilizing the Services offered by the TSP.</li>
                                <li>Xpress Move encourages all its customers to take full responsibility of his/her items. In case of
lost items inside during the journey, Xpress Move will try to locate the items on a "besteffort"
basis but is not responsible for the same in case of loss or damage to the same.</li>
                                <li>All the calls made to the Xpress Move's CC are recorded by company for quality and training
purposes.</li>
                                <li>Tolls and extra fares as applicable are to be paid by the user.</li>
                                         <p style="text-align:justify;"><b>The customer shall ensure that he/she will not indulge in any of the following activities while
in goods carrier:</b></p>
                                 <ol type="A"  style="margin-left:40px;">
                                     <li>Asking the driver to break any Traffic/Transport/City Police and/or government rules for
any purpose (especially reaching the destination earlier).</li>
                                     <li>Pressurizing the driver to overload the boot space of the vehicle with luggage. The
customer shall not be generally allowed to use the seating area of the vehicles for placing
any kind of luggage.</li>
                                     <li>Customer should not soil or damage the body and/or any other interiors of goods carrier.</li>
                                     </ol>
                                    
                                 </ul>
                                 <h2>Representation, Warranties, Indemnification And Limitation Of
Liability</h2>
                                  <p style="text-align:justify;"><b>Without prejudice to the above, Xpress Move makes no representation or warranty that:</b></p>
                                  <ul style="list-style-type:circle;margin-left:20px;" >
                     <li>The Services will always meet the customer's requirements.</li>
                                <li>The Services will be uninterrupted, timely or errorfree</li>
                                <li>Xpress Move shall not be responsible or liable for any loss or damage, howsoever caused or
suffered by the Customer arising out of the use of transportation service offered by TSP
or due to the failure of TSP to provide Services to the Customer for any reason
whatsoever including but not limited to the Customer's noncompliance
with the Services'
recorded voice instructions, malfunction, partial or total failure of any network terminal,
data processing system, computer or telecommunications system or other circumstances
whether or not beyond the control of Xpress Move or any person or any organization
involved in the above mentioned systems.</li>
                                <li>Xpress Move will not be liable for any damages of any kind arising from the use of the
Service offered by the TSP including, but not limited to direct, indirect, incidental,
punitive, and consequential damages.</li>
                                <li>Xpress Move shall not be liable for any loss or damages, including any injury which you
may suffer as a result of your vehicles journey in a participating vehicles hired through the services and all your rights in relation thereto and in relation to the contract for hire
between you and the relevant Participating vehicles shall be a matter between you and the
relevant Participating vehicles.</li>
                                         <li>Xpress Move will take all reasonable measures to ensure that TSP should fulfill his duty
properly but there may be exceptions and if any delay, direct and indirect loss occurs ,
Xpress Move will not be held liable for any such compensation.</li>
                                      <li>The customer is advised to make alternate arrangement in the case vehicle has not
reached due to any reason.</li>
                                      <li>Xpress Move shall not be liable for any conduct of the drivers. Xpress Move encourages you
to notify any complaints that you may have against the driver before requisite authority.</li>
                                      <li><b>We are not liable if we do not fulfill any obligations towards you because of following
(but not limited to):</b>
                                 <ol type="A" style="margin-left:40px;">
                                     <li>Acts of god such as flooding, fire, earthquakes, cyclones, storms or other (but
not limited to) natural calamities or disasters.</li>
                                     <li>Force majeure such as (but not limited to) war, accidents, acts of public
enemies, strikes, embargoes, perils of the air, local disputes or civil
commotions.</li>
                                     <li>National or local disruptions in air or ground transportation networks and
mechanical problems to modes of transport or machinery.</li>
                                        <li>Criminal acts of third parties such as theft and arson.</li>
                                     </ol>
                                          </li>
                                 </ul>
                                 
                                <p style="text-align:justify;"><b>We are not liable if we do not fulfill any obligations towards you because of following
(but not limited to):</b></p>
                             <h2>Illegal/Prohibited Goods/Security</h2> 
                                         
                               <p style="text-align:justify;">W e do not carry, nor perform other services in relation to goods which are not limited in our
sole opinion dangerous goods including, but on that of the regulations, directives, technical
manuals, codes for us and our business, or for the transport limits specified, or the provision of
other services in respect of dangerous goods.We may at our discretion accept some dangerous
goods for carriage or the provision of other services, in some places, if you have granted the
status of approved customer and this must be given by us in writing before your shipment can be
accepted. Your dangerous goods will only be accepted if they comply with the relevant
regulations and our requirements. Details of our requirements together with the procedure for
applying for approved customer status are from our nearest office and a dangerous goods
surcharge available is provided to you upon acceptance of your shipment bill.
We do not accept shipments that contain prohibited items. We accept shipments only after your
explanation of the nature and value of the shipment ("I said, included" basis). We have no
responsibility for the correctness of description, type, or value thereof, and you agree to indemnify us and keep us from any claims that may be brought against us arising from or in
connection with this statement by you and any costs provided to us may arise will entrust traffic.</p>  
                                        
                    <h2>Rejected Consignments</h2> 
                             <p style="text-align:justify;">If the receiver refuses to accept delivery we will try to contact user and agree the appropriate
next action. User agrees to pay the Company any costs we incur in forwarding, disposing of or
returning the consignment and our charges (if any) for the agreed appropriate next action</p> 
                               <h2>Amendment To Terms Of Contract</h2> 
                             <p style="text-align:justify;">Xpress Move shall be entitled to add, vary or amend any or all these terms and conditions at any
time without any prior notification to user(s). Customer shall be bound by such addition,
variation or amendment from the date that such addition, variation or amendment are
incorporated into these terms and conditions at website and/or the Application.</p> 
                              <h2>Consent To Electronic Communications And Transactions</h2>
                            <p style="text-align:justify;">By using our website/application/service, you consent to conduct transactions and receive
communications, notices and information from us electronically, whether sent by email
or other
electronic means. Electronic communications shall be deemed to have been received by you
when we send the electronic communication to the email address / mobile number that as per our
records, or when we post the electronic communication on the Application or the Website.</p> 
                             <h2>Choice Of law And Dispute Resolution</h2>
                             <p style="text-align:justify;">These Terms shall be governed by, and construed in accordance with, the laws of India, without
reference to principles of conflicts of law. The parties agree that the courts of Pune shall have
exclusive jurisdiction over any dispute arising from or relating to these Terms, Service, the
Application or the Website. You expressly consent to the personal jurisdiction of said courts and
waive any objection to such personal jurisdiction based on forums non convenience or any other
basis.</p> 
					</article>
					<!-- //Post -->
				</div>
				<!--- //Content -->
				
				<!--- Sidebar -->
				<aside class="one-fourth sidebar right">
					<!-- Widget -->
					<!-- //Widget -->
					
					<!-- Widget -->
					<div class="widget">
						<h4>Need help for booking?</h4>
						<div class="textwidget">
							<p>Our customer care will help you for all transportation needs.</p>
							<p class="contact-data"><img src="catalog/view/theme/default/image/callicon.png" style="height:32px"> +91 8698-123-444</p>
						</div>
					</div>
					<!-- //Widget -->
				</aside>
		</div>
                </div>
            </div><!--- //Sidebar -->
	
	</main>